################
# 0 #
################

[[word]]
ru = ""
de = ""
syn = ""
[[word.ex]]
de = ""
ru = ""
[[word.ex]]
de = ""
ru = ""
[[word.ex]]
de = ""
ru = ""



[word.kon]
"pres" = ""
"prat" = ""
"perfekt" = ""



