################
# 2 #
################

[[word]]
ru = "сказка"
de = "das Märchen"
[[word.ex]]
de = "das Zaubermärchen, das Kindermärchen, das Volksmärchen"
ru = "волшебная сказка, детская сказка, народная сказка"
[[word.ex]]
de = "die Märchen der Brüder Grimm"
ru = "сказки братьев Гримм"
[[word.ex]]
de = "das klingt wie ein Märchen"
ru = "это звучит как сказка"
[[word.ex]]
de = "erzähle mir nur keine Märchen!"
ru = "Только не рассказывайте мне сказки"

[[word]]
ru = "рассказ"
de = "die Er­zäh­lung"
[[word.ex]]
de = "in seiner Erzählung fortfahren"
ru = "продолжить свой рассказ"
[[word.ex]]
de = "Erzählungen schreiben"
ru = "Писать истории"

[[word]]
ru = "история"
de = "die Geschichte"
[[word.ex]]
de = "die Geschichte der Menschheit"
ru = "история человечества"
[[word.ex]]
de = "sie ist Professorin für Geschichte"
ru = " она профессор истории"
[[word.ex]]
de = "eine Geschichte vorlesen"
ru = "прочитать историю"

[[word]]
ru = "стихотворение"
de = "das Gedicht"
[[word.ex]]
de = "ein Gedicht lernen"
ru = "выучить стихотворение"

[[word]]
ru = "книга"
de = "das Buch"
[[word.ex]]
de = "ein dickes Buch"
ru = "толстая книга"
[[word.ex]]
de = "ein spannendes Buch"
ru = "захватывающая книга"
[[word.ex]]
de = "er hat immer ein kleines Buch bei sich, in dem er sich Notizen macht"
ru = "у него всегда с собой маленькая книжка, в которой он делает записи"
[[word.ex]]
de = "die Bücher führen"
ru = "вести бухгалтерию"

[[word]]
ru = "рассказывать"
de = "erzählen"
[[word.ex]]
de = "gut erzählen können"
ru = "уметь хорошо рассказывать истории"
[[word.ex]]
de = "den Kindern ein Märchen erzählen"
ru = " расскать детям сказку"
[[word.ex]]
de = "er hat viel über ihn erzählt"
ru = " он много говорил о нем"
[[word.ex]]
de = "du darfst aber niemandem davon erzählen"
ru = "Но ты не можешь никому об этом рассказат"
[word.kon]
"pres" = "er erzählt"
"prat" = "er erzählte"
"perfekt" = "er hat erzählt"

[[word]]
ru = "читать"
de = "lesen"
[[word.ex]]
de = "laut, leise, schnell, langsam lesen"
ru = "громко, тихо, быстро, медленно читать"
[[word.ex]]
de = "aus seinem Blick, Gesicht war deutlich zu lesen, was er dachte"
ru = "По выражению его лица было ясно, о чем он думает."
[[word.ex]]
de = "Gedanken lesen, erraten können"
ru = "Умение читать, угадывать мысли"
[[word.ex]]
de = "das Buch liest sich leicht, flüssig"
ru = "Книга читается легко, динамично"
[word.kon]
"pres" = "er liest"
"prat" = "er las"
"perfekt" = "er hat gelesen"

