################
# 8 #
################

громко тихо laut leise
мягко твердо weich hart
быстро медленно schnell langsam
schön красиво hässlich некрасиво
дружелюбный freundlich
чужой fremd
dumm глупый klug умный
свежий frisch
ähnlich unähnlich похожий непохожий
früh spät ранний поздний 
настоящий echt
известный, знакомый bekannt
смелый mutig трусливый feige
ruhig спокойный
vorsichtig осторожный
falsch неправильный richtig правильный
дорогой дешевый
богатый бедный
целый
пустой полный


[[word]]
ru = ""
de = ""
syn = ""
[[word.ex]]
de = ""
ru = ""
[[word.ex]]
de = ""
ru = ""
[[word.ex]]
de = ""
ru = ""

[[word]]
ru = ""
de = ""
syn = ""
[[word.ex]]
de = ""
ru = ""
[[word.ex]]
de = ""
ru = ""
[[word.ex]]
de = ""
ru = ""

[[word]]
ru = ""
de = ""
syn = ""
[[word.ex]]
de = ""
ru = ""
[[word.ex]]
de = ""
ru = ""
[[word.ex]]
de = ""
ru = ""


[word.kon]
"pres" = ""
"prat" = ""
"perfekt" = ""



